### ISSUE TITLE
"Running Locally" instructions outdated?

### ISSUE THREAD

**Issue by mdrxy** [aidansmth/API_relay#2]
Hi @aidansmth, great tool here! I wanted to note the following observations -- perhaps they were true at one point and then the README didn't get updated after things changed? Regardless, I wanted to leave this here in case anyone else trying to run this faced similar issues.
* `SPINITRON_API_KEY` seems like it should instead be `SPIN_KEY` based on the current source code
* Using a `.env` file doesn't appear to be implemented - I've had to use `export SPIN_KEY="{key}"`
* Running locally outside of a container (with `LOCAL=OK`), the service is available at port 8080 `localhost:8080` by default.

As an aside, `FROM rust as build` in the Dockerfile should be written `FROM rust AS build` to prevent the `FromAsCasing` warning when building.

After building the image, the best command to run the container I've found is to use:
```sh
docker run -d --name {CHOOSE CONTAINER NAME} -p 80:80 -e SPIN_KEY="{SPINITRON API KEY}" --restart unless-stopped {IMAGE NAME}
```

**Comment by aidansmth** [comment]
Hi Mason- the README likely is old.

Thanks for bringing these issues up– I'll look into them.
Cheers!

**Comment by aidansmth** [comment]
@mdrxy Could you check over the readme and code changes in 5480393234d2f5328d6894fba8435b49c81ff639 and give me your thoughts? Thanks

**Comment by mdrxy** [comment]
Looks pretty good - kudos! I tested up through Docker but didn't run w/ compose or AWS.
